name: llmgo

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: llmgo-app
  #   ports:
  #     - "8080:8080" # Optional, if your app exposes a port
  #   depends_on:
  #     - redis
  #   command: ["go", "run", "./whatsmeow"]
volumes:
  redis-data:
